# Generated by Django 5.2.4 on 2025-08-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_migrate_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imuplan',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='imuplan',
            name='plan_status',
        ),
        migrations.RemoveField(
            model_name='imuplan',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='imuplan',
            name='status',
        ),
    ]
