# Generated by Django 5.2.4 on 2025-09-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_lesson_deleted_at_lesson_is_deleted'),
        ('plans', '0006_alter_imuplan_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuplan',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson', verbose_name='Pamoka'),
        ),
    ]
