# backend/grades/migrations/0001_initial.py
# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(help_text='Vertinimas procentais (0-100)', validators=[django.core.validators.MinValueValidator(0, 'Procentai negali būti mažiau nei 0'), django.core.validators.MaxValueValidator(100, 'Procentai negali būti daugiau nei 100')], verbose_name='Procentai')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='curriculum.lesson', verbose_name='Pamoka')),
            ],
            options={
                'verbose_name': 'Pažymys',
                'verbose_name_plural': 'Pažymiai',
                'ordering': ['-created_at'],
            },
        ),
    ]
