# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Klasės pavadinimas', max_length=100, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, help_text='Klasės aprašymas', verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Klasė',
                'verbose_name_plural': 'Klasės',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(help_text='Pamokos pradžios laikas', verbose_name='Pradžios laikas')),
                ('endtime', models.TimeField(help_text='Pamokos pabaigos laikas', verbose_name='Pabaigos laikas')),
                ('duration', models.IntegerField(help_text='Pamokos trukmė minutėmis', verbose_name='Trukmė minutėmis')),
            ],
            options={
                'verbose_name': 'Periodas',
                'verbose_name_plural': 'Periodai',
                'ordering': ['starttime'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Pamokos data', verbose_name='Data')),
                ('weekday', models.CharField(help_text='Savaitės diena', max_length=20, verbose_name='Savaitės diena')),
                ('classroom', models.ForeignKey(help_text='Pamokos klasė', on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Klasė')),
                ('lesson', models.ForeignKey(help_text='Pamokos šablonas', on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson', verbose_name='Pamoka')),
                ('level', models.ForeignKey(help_text='Mokymo lygis', on_delete=django.db.models.deletion.CASCADE, to='curriculum.level', verbose_name='Lygis')),
                ('subject', models.ForeignKey(help_text='Mokomas dalykas', on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Dalykas')),
            ],
            options={
                'verbose_name': 'Globalus tvarkaraštis',
                'verbose_name_plural': 'Globalus tvarkaraštis',
                'ordering': ['date', 'period__starttime'],
            },
        ),
    ]
