# Generated by Django 5.2.4 on 2025-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['name'], 'verbose_name': 'Periodas', 'verbose_name_plural': 'Periodai'},
        ),
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(blank=True, help_text='Periodo pavadinimas (pvz. 1 pamoka, 2 pamoka)', max_length=100, null=True, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='period',
            name='duration',
            field=models.IntegerField(default=45, help_text='Pamokos trukmė minutėmis', verbose_name='Trukmė minutėmis'),
        ),
        migrations.AlterField(
            model_name='period',
            name='endtime',
            field=models.TimeField(blank=True, help_text='Pamokos pabaigos laikas (HH:MM) - skaičiuojamas automatiškai', null=True, verbose_name='Pabaigos laikas'),
        ),
        migrations.AlterField(
            model_name='period',
            name='starttime',
            field=models.TimeField(help_text='Pamokos pradžios laikas (HH:MM)', verbose_name='Pradžios laikas'),
        ),
    ]
