# backend/schedule/migrations/0004_limit_user_to_mentors.py
# Generated by Django 5.2.4 on 2025-08-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_add_period_name_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalschedule',
            name='user',
            field=models.ForeignKey(help_text='Pamokos vedėjas (tik mentoriai)', limit_choices_to={'roles__contains': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentorius'),
        ),
    ]
