# Generated by Django 5.2.4 on 2025-08-06 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_limit_user_to_mentors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalschedule',
            name='user',
            field=models.ForeignKey(help_text='Pamokos vedėjas (tik mentoriai)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentorius'),
        ),
    ]
