# Generated by Django 5.2.4 on 2025-08-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_old_lesson_fields'),
        ('schedule', '0005_remove_limit_choices_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalschedule',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Pamokos šablonas (neprivaloma)', null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson', verbose_name='Pamoka'),
        ),
        migrations.AlterField(
            model_name='globalschedule',
            name='weekday',
            field=models.CharField(blank=True, help_text='Savaitės diena (skaičiuojama automatiškai)', max_length=20, null=True, verbose_name='Savaitės diena'),
        ),
    ]
