# Generated by Django 5.2.4 on 2025-08-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_make_weekday_auto_and_lesson_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['starttime'], 'verbose_name': 'Periodas', 'verbose_name_plural': 'Periodai'},
        ),
    ]
