# backend/schedule/migrations/0008_remove_globalschedule_lesson.py
# Generated by Django 5.2.4 on 2025-08-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_change_period_ordering_to_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalschedule',
            name='lesson',
        ),
    ]
