# Generated by Django 5.2.4 on 2025-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_globalschedule_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalschedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Veiklos pabaigos laikas', null=True, verbose_name='Baigta'),
        ),
        migrations.AddField(
            model_name='globalschedule',
            name='plan_status',
            field=models.CharField(choices=[('planned', 'Suplanuota'), ('in_progress', 'Vyksta'), ('completed', 'Baigta')], default='planned', help_text='Ugdymo plano būsena: suplanuota, vyksta, baigta', max_length=20, verbose_name='Plano būsena'),
        ),
        migrations.AddField(
            model_name='globalschedule',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Veiklos pradžios laikas', null=True, verbose_name='Pradėta'),
        ),
    ]
