# Generated by Django 5.2.4 on 2025-09-02 14:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategorijos pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('color_type', models.CharField(choices=[('DEFAULT', 'Default'), ('RED', 'Raudona'), ('BLUE', 'Mėlyna'), ('YELLOW', 'Geltona'), ('ORANGE', 'Oranžinė'), ('PURPLE', 'Violetinė'), ('GREEN', 'Žalia'), ('DARK_GREEN', 'Tamsiai žalia'), ('AMBER', 'Geltona-oranžinė'), ('DARK_RED', 'Tamsiai raudona')], default='DEFAULT', help_text='Spalvos tipas kategorijai. Naudojama lentelės eilutėms spalvinti.', max_length=20, verbose_name='Spalvos tipas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Pažeidimo kategorija',
                'verbose_name_plural': 'Pažeidimo kategorijos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ViolationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rėžio pavadinimas')),
                ('min_violations', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimalus pažeidimų skaičius')),
                ('max_violations', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimalus pažeidimų skaičius (palikti tuščią jei neribotas)')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mokesčio dydis (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Pažeidimų rėžis',
                'verbose_name_plural': 'Pažeidimų rėžiai',
                'ordering': ['min_violations'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_violations__isnull', True), ('max_violations__gte', models.F('min_violations')), _connector='OR'), name='max_violations_gte_min_violations')],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo pavadinimas')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Numatytoji suma')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='violation.violationcategory', verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Pažeidimo tipas',
                'verbose_name_plural': 'Pažeidimo tipai',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50, verbose_name='Pažeidimo tipas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valiuta')),
                ('status', models.CharField(choices=[('pending', 'Neatlikta'), ('completed', 'Skola išpirkta')], default='pending', max_length=20, verbose_name='Užduoties statusas')),
                ('penalty_status', models.CharField(choices=[('unpaid', 'Neapmokėta'), ('paid', 'Apmokėta')], default='unpaid', max_length=20, verbose_name='Mokesčio statusas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('task_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Užduotis atlikta')),
                ('penalty_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Mokestis apmokėtas')),
                ('category', models.CharField(max_length=50, verbose_name='Kategorija')),
                ('violation_count', models.PositiveIntegerField(default=1, verbose_name='Pažeidimų skaičius mokiniui')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mokesčio dydis (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Papildomi komentarai')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_violations', to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name='Mokinys')),
            ],
            options={
                'verbose_name': 'Pažeidimas/Skola',
                'verbose_name_plural': 'Pažeidimai/Skolos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='violation_v_student_32eff7_idx'), models.Index(fields=['student', 'penalty_status'], name='violation_v_student_95b431_idx'), models.Index(fields=['category', 'status'], name='violation_v_categor_567684_idx'), models.Index(fields=['violation_count'], name='violation_v_violati_3dee35_idx')],
            },
        ),
    ]
