# Generated by Django 5.2.4 on 2025-09-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0002_remove_violation_type_add_todos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViolationType',
        ),
    ]
