# Generated by Django 5.2.4 on 2025-09-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0003_remove_violation_type_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='currency',
        ),
    ]
