# Generated by Django 5.2.4 on 2025-08-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        # First, delete any lessons that have null subjects
        migrations.RunSQL(
            "DELETE FROM crm_lesson WHERE subject_id IS NULL;",
            reverse_sql=""
        ),
        
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                verbose_name='Dalykas',
                to='crm.subject'
            ),
        ),
    ]
