# Generated by Django 5.2.4 on 2025-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250801_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='components',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='skills',
        ),
        migrations.AddField(
            model_name='lesson',
            name='competencies',
            field=models.TextField(blank=True, help_text='Kompetencijos JSON formatu', verbose_name='Kompetencijos'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='components',
            field=models.TextField(blank=True, help_text='Komponentai JSON formatu', verbose_name='Komponentai'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='focus',
            field=models.TextField(blank=True, help_text='Dėmesio kryptys JSON formatu', verbose_name='Dėmesio kryptys'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objectives',
            field=models.TextField(blank=True, help_text='Tikslai JSON formatu', verbose_name='Tikslai'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skills',
            field=models.TextField(blank=True, help_text='Gebėjimai JSON formatu', verbose_name='Gebėjimai'),
        ),
    ]
