# Generated by Django 5.2.4 on 2025-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_lesson_competencies_remove_lesson_components_and_more'),
    ]

    operations = [
        # Pašalinti Topic modelį
        migrations.DeleteModel(
            name='Topic',
        ),
        # Pakeisti topic laukelį iš ForeignKey į CharField
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Tema'
            ),
        ),
    ]
