# Generated by Django 5.2.4 on 2025-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20250801_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='aukstesnysis',
            field=models.TextField(blank=True, help_text='Aukštesniojo lygio reikalavimai', verbose_name='Aukštesnysis lygis (100%)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='bazinis',
            field=models.TextField(blank=True, help_text='Bazinio lygio reikalavimai', verbose_name='Bazinis lygis (74%)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pagrindinis',
            field=models.TextField(blank=True, help_text='Pagrindinio lygio reikalavimai', verbose_name='Pagrindinis lygis (84%)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='slenkstinis',
            field=models.TextField(blank=True, help_text='Slenkstinio lygio reikalavimai', verbose_name='Slenkstinis lygis (54%)'),
        ),
    ]
