# Generated by Django 5.2.4 on 2025-08-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lesson_aukstesnysis_lesson_bazinis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sutrumpintas kodas'),
        ),
        migrations.AddField(
            model_name='skill',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.subject', verbose_name='Dalykas'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Pavadinimas'),
        ),
    ]
