# Generated by Django 5.2.4 on 2025-08-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_skill_code_skill_subject_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kompetencijos pavadinimas'),
        ),
        migrations.CreateModel(
            name='CompetencyAtcheve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.TextField(blank=True, help_text='Veiksmai, kuriuos reikia atlikti', verbose_name='Todo sąrašas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.competency', verbose_name='Kompetencija')),
                ('virtues', models.ManyToManyField(to='crm.virtue', verbose_name='Dorybės')),
            ],
            options={
                'verbose_name': 'Kompetencijos pasiekimas',
                'verbose_name_plural': 'Kompetencijų pasiekimai',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='competency_atcheve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.competencyatcheve', verbose_name='Kompetencijos pasiekimas'),
        ),
    ]
