# Generated by Django 5.2.4 on 2025-08-03 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_competency_name_competencyatcheve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyatcheve',
            options={'verbose_name': 'Kompetencijos pasiekimas', 'verbose_name_plural': 'Kompetencijų pasiekimai'},
        ),
        migrations.RemoveField(
            model_name='competencyatcheve',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competencyatcheve',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='competencyatcheve',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.subject', verbose_name='Dalykas'),
        ),
    ]
