# Generated by Django 5.2.4 on 2025-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_competencyatcheve_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='skills',
        ),
        migrations.AddField(
            model_name='lesson',
            name='skills',
            field=models.ManyToManyField(blank=True, to='crm.skill', verbose_name='Gebėjimai'),
        ),
    ]
