# Generated by Django 5.2.4 on 2025-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_lesson_skills_lesson_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='competency_atcheve',
        ),
        migrations.AddField(
            model_name='lesson',
            name='competency_atcheves',
            field=models.ManyToManyField(blank=True, to='crm.competencyatcheve', verbose_name='Kompetencijos pasiekimai'),
        ),
    ]
