# Generated by Django 5.2.4 on 2025-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_lesson_competency_atcheve_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencyatcheve',
            options={'verbose_name': 'BUP Kompetencija', 'verbose_name_plural': 'BUP Kompetencijos'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='competency_atcheves',
            field=models.ManyToManyField(blank=True, to='crm.competencyatcheve', verbose_name='BUP Kompetencijos'),
        ),
    ]
