# Generated by Django 5.2.4 on 2025-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_competencyatcheve_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='focus',
            field=models.TextField(blank=True, help_text='Fokusas veiksmai JSON formatu', verbose_name='Fokusas veiksmai'),
        ),
    ]
