# Generated by Django 5.2.4 on 2025-08-10 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_remove_old_lesson_fields'),
        ('schedule', '0008_remove_globalschedule_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('created_by', models.ForeignKey(blank=True, help_text='Kas sukūrė šią seką (nebūtina)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.level', verbose_name='Lygis')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Dalykas')),
            ],
            options={
                'verbose_name': 'Pamokų seka',
                'verbose_name_plural': 'Pamokų sekos',
                'unique_together': {('name', 'subject', 'level')},
            },
        ),
        migrations.CreateModel(
            name='IMUPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Suplanuota'), ('in_progress', 'Vyksta'), ('completed', 'Baigta'), ('missed', 'Praleista'), ('cancelled', 'Atšaukta')], default='planned', max_length=20, verbose_name='Būsena')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Pradėta')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Baigta')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('global_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.globalschedule', verbose_name='Veikla (GlobalSchedule)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson', verbose_name='Pamoka')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imu_plans', to=settings.AUTH_USER_MODEL, verbose_name='Mokinys')),
            ],
            options={
                'verbose_name': 'Individualus mokinio ugdymo planas',
                'verbose_name_plural': 'Individualūs mokinių ugdymo planai',
                'unique_together': {('student', 'global_schedule')},
            },
        ),
        migrations.CreateModel(
            name='LessonSequenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Eiliškumas')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson', verbose_name='Pamoka')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.lessonsequence', verbose_name='Seka')),
            ],
            options={
                'verbose_name': 'Sekos elementas',
                'verbose_name_plural': 'Sekos elementai',
                'ordering': ['position'],
                'unique_together': {('sequence', 'position')},
            },
        ),
    ]
