# Generated by Django 5.2.4 on 2025-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuplan',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Dalyvavo'), ('absent', 'Nedalyvavo'), ('late', 'Vėlavo'), ('excused', 'Pateisinta')], default='present', help_text='Mokinio lankomumo būsena: dalyvavo, nedalyvavo, vėlavo, pateisinta', max_length=20, verbose_name='Lankomumo būsena'),
        ),
        migrations.AddField(
            model_name='imuplan',
            name='plan_status',
            field=models.CharField(choices=[('planned', 'Suplanuota'), ('in_progress', 'Vyksta'), ('completed', 'Baigta')], default='planned', help_text='Ugdymo plano būsena: suplanuota, vyksta, baigta', max_length=20, verbose_name='Plano būsena'),
        ),
        migrations.AlterField(
            model_name='imuplan',
            name='status',
            field=models.CharField(choices=[('planned', 'Suplanuota'), ('in_progress', 'Vyksta'), ('completed', 'Baigta'), ('present', 'Dalyvavo'), ('absent', 'Nedalyvavo'), ('late', 'Vėlavo'), ('excused', 'Pateisinta')], default='planned', help_text='SENAS STULPELIS - bus pašalintas po migracijos', max_length=20, verbose_name='Būsena (senas)'),
        ),
    ]
