# Generated by Django 5.2.4 on 2025-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_lesson_deleted_at_lesson_is_deleted'),
        ('plans', '0004_remove_imuplan_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuplan',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Dalyvavo'), ('absent', 'Nedalyvavo'), ('late', 'Vėlavo'), ('excused', 'Pateisinta')], default=None, help_text='Mokinio lankomumo būsena: dalyvavo, nedalyvavo, vėlavo, pateisinta', max_length=20, null=True, verbose_name='Lankomumo būsena'),
        ),
        migrations.AlterField(
            model_name='lessonsequenceitem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lesson', verbose_name='Pamoka'),
        ),
    ]
