# Generated by Django 5.2.4 on 2025-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_change_late_to_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuplan',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Dalyvavo'), ('absent', 'Nedalyvavo'), ('left', 'Paliko'), ('excused', 'Pateisinta')], default=None, help_text='Mokinio lankomumo būsena: dalyvavo, nedalyvavo, vėlavo, pateisinta', max_length=20, null=True, verbose_name='Lankomumo būsena'),
        ),
    ]
