# Generated by Django 5.2.4 on 2025-09-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='violation_type',
        ),
        migrations.AddField(
            model_name='violation',
            name='todos',
            field=models.JSONField(blank=True, default=list, help_text='ToDo sąrašas užduočių, kurias reikia atlikti dėl pažeidimo', verbose_name='Užduočių sąrašas'),
        ),
    ]
