# /backend/crm/migrations/0002_initial.py
# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsubject',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_subjects', to=settings.AUTH_USER_MODEL, verbose_name='mentor'),
        ),
        migrations.AddField(
            model_name='mentorsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='studentcurator',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_students', to=settings.AUTH_USER_MODEL, verbose_name='curator'),
        ),
        migrations.AddField(
            model_name='studentcurator',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_curators', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_students', to=settings.AUTH_USER_MODEL, verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='studentsubjectlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.level', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='studentsubjectlevel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_levels', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddField(
            model_name='studentsubjectlevel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='subject'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorsubject',
            unique_together={('mentor', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcurator',
            unique_together={('student', 'curator', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentparent',
            unique_together={('student', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectlevel',
            unique_together={('student', 'subject', 'level')},
        ),
    ]
