# Generated by Django 5.2.4 on 2025-09-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorsubject',
            unique_together=set(),
        ),
    ]
