# backend/curriculum/migrations/0002_initial.py
# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_mentored', to=settings.AUTH_USER_MODEL, verbose_name='Mentorius'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='levels',
            field=models.ManyToManyField(blank=True, to='curriculum.level', verbose_name='Mokymo lygiai'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skills',
            field=models.ManyToManyField(blank=True, to='curriculum.skill', verbose_name='Gebėjimai'),
        ),
        migrations.AddField(
            model_name='skill',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Dalykas'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Dalykas'),
        ),
        migrations.AddField(
            model_name='competencyatcheve',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject', verbose_name='Dalykas'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='virtues',
            field=models.ManyToManyField(blank=True, to='curriculum.virtue', verbose_name='Dorybės'),
        ),
        migrations.AddField(
            model_name='competencyatcheve',
            name='virtues',
            field=models.ManyToManyField(to='curriculum.virtue', verbose_name='Dorybės'),
        ),
    ]
