# Generated by Django 5.2.4 on 2025-08-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_lesson_description_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='assessment_criteria',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='competencies',
        ),
    ]
