# Generated by Django 5.2.4 on 2025-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_old_lesson_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ištrinta'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Ištrinta'),
        ),
    ]
