# backend/curriculum/migrations/0001_initial.py
# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompetencijos pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Kompetencija',
                'verbose_name_plural': 'Kompetencijos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Komponentas',
                'verbose_name_plural': 'Komponentai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Mokymo lygis',
                'verbose_name_plural': 'Mokymo lygiai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Tikslas',
                'verbose_name_plural': 'Tikslai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sutrumpintas kodas')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Gebėjimas',
                'verbose_name_plural': 'Gebėjimai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Dalykas',
                'verbose_name_plural': 'Dalykai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Virtue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Dorybė',
                'verbose_name_plural': 'Dorybės',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyAtcheve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todos', models.TextField(blank=True, help_text='Veiksmai, kuriuos reikia atlikti', verbose_name='Todo sąrašas')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.competency', verbose_name='Kompetencija')),
            ],
            options={
                'verbose_name': 'BUP Kompetencija',
                'verbose_name_plural': 'BUP Kompetencijos',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('assessment_criteria', models.TextField(blank=True, verbose_name='Vertinimo kriterijai')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Tema')),
                ('objectives', models.TextField(blank=True, help_text='Tikslai JSON formatu', verbose_name='Tikslai')),
                ('components', models.TextField(blank=True, help_text='Komponentai JSON formatu', verbose_name='Komponentai')),
                ('competencies', models.TextField(blank=True, help_text='Kompetencijos JSON formatu', verbose_name='Kompetencijos')),
                ('focus', models.TextField(blank=True, help_text='Fokusas veiksmai JSON formatu', verbose_name='Fokusas veiksmai')),
                ('slenkstinis', models.TextField(blank=True, help_text='Slenkstinio lygio reikalavimai', verbose_name='Slenkstinis lygis (54%)')),
                ('bazinis', models.TextField(blank=True, help_text='Bazinio lygio reikalavimai', verbose_name='Bazinis lygis (74%)')),
                ('pagrindinis', models.TextField(blank=True, help_text='Pagrindinio lygio reikalavimai', verbose_name='Pagrindinis lygis (84%)')),
                ('aukstesnysis', models.TextField(blank=True, help_text='Aukštesniojo lygio reikalavimai', verbose_name='Aukštesnysis lygis (100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('competency_atcheves', models.ManyToManyField(blank=True, to='curriculum.competencyatcheve', verbose_name='BUP Kompetencijos')),
            ],
            options={
                'verbose_name': 'Pamoka',
                'verbose_name_plural': 'Pamokos',
                'ordering': ['-created_at'],
            },
        ),
    ]
