# Generated by Django 5.2.4 on 2025-09-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_fix_competencyatcheve_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sutrumpintas kodas'),
        ),
    ]
