# Generated by Django 5.2.4 on 2025-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_remove_skill_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#fecaca', help_text='HEX spalvos kodas (pvz., #fecaca)', max_length=7, verbose_name='Spalva'),
        ),
    ]
