# backend/schedule/migrations/0002_initial.py
# Generated by Django 5.2.4 on 2025-08-05 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='globalschedule',
            name='user',
            field=models.ForeignKey(help_text='Pamokos vedėjas (tik mentoriai)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentorius'),
        ),
        migrations.AddField(
            model_name='globalschedule',
            name='period',
            field=models.ForeignKey(help_text='Pamokos periodas', on_delete=django.db.models.deletion.CASCADE, to='schedule.period', verbose_name='Periodas'),
        ),
        migrations.AlterUniqueTogether(
            name='globalschedule',
            unique_together={('date', 'period', 'classroom')},
        ),
    ]
