# Generated by Django 5.2.4 on 2025-09-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_role',
            field=models.CharField(blank=True, help_text='Numatytoji rolė prisijungimo metu', max_length=20, null=True, verbose_name='default role'),
        ),
    ]
